-- Create the equipement_historique table if it doesn't exist
create table if not exists public.equipement_historique (
  id bigint generated by default as identity primary key,
  id_ordinateur uuid references public.ordinateurs(id_ordinateur) on delete cascade not null,
  id_employe bigint references public.employe(id_employe) on delete set null,
  date_debut timestamp with time zone default timezone('utc'::text, now()) not null,
  date_fin timestamp with time zone,
  type_action text not null, -- 'affectation', 'restitution', 'creation', 'modification'
  commentaire text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies (optional, but good practice)
alter table public.equipement_historique enable row level security;

create policy "Enable read access for all users" on public.equipement_historique
  for select using (true);

create policy "Enable insert access for all users" on public.equipement_historique
  for insert with check (true);

create policy "Enable update access for all users" on public.equipement_historique
  for update using (true);
